FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install --omit=dev && npm install --no-save typescript ts-node

COPY . .

RUN npm run build

EXPOSE 4000
CMD ["node", "dist/index.js"]
